### PR TITLE
Travis CI

### PR DESCRIPTION
**Pull request by jeffhammond**
Do not merge this yet.  I rebased and need to verify that it is not broken.

### CODE REVIEW

**Comment by minsii** [comment]
It looks all tests passed except ompi + osx. Search `all passed` for other logs. About the error in ompi + osx, have you seem this before ? I did not see such error on Jenkins ompi + osx run.
"ORTE_ERROR_LOG: Bad parameter in file orted/pmix/pmix_server.c at line 262"

**Comment by jeffhammond** [comment]
I don't see anything failing in https://travis-ci.org/pmodels/casper/builds/211946540.  Where are you seeing the error?

However, the error you describe is https://github.com/open-mpi/ompi/issues/2956#issuecomment-285343579 and I am very familiar, having had to push the same fix to all of MPI-based projects recently.

**Comment by jeffhammond** [comment]
I pushed the fix for this in https://github.com/pmodels/casper/pull/20/commits/dbde7d2029f15b369b5cf4e5ef8d20e6dd093d14.

**Comment by minsii** [comment]
Not sure why travis does not correctly cache such failing.  But you can find the error message in raw log. I guess junit xml output might be easier for travis to cache error.

**Comment by jeffhammond** [comment]
I don't know what is wrong with OMPI yet but I just set to XFAIL in Travis.  This PR is ready for merge.

**Comment by minsii** [comment]
What do you think about the comments in travis/build-run.sh ?  The lines after `# Run real tests` seem unnecessary.

**Comment by jeffhammond** [comment]
Hmm, those lines might be leftovers from MPICH Travis.  I removed them.

**Pull request merged**
